hpcc-systems/wssql

esp/services/ws_sql/SQL2ECL/HPCCFile.cpp
=> WSSQL-53 Fix break due to platform change

version.cmake
=> #INTERNAL update version on master to 5.2 trunk

esp/services/ws_sql/SQL2ECL/HPCCFile.hpp, esp/services/ws_sql/SQL2ECL/HPCCFileCache.cpp
=> WSSQL-49 Add Description field, and populate

esp/scm/ws_sql.ecm
=> WSSQL-45 Remove unused field

CMakeLists.txt, platform-version-prereq.cmake
=> WSSQL-55 Change versioning to match platform

esp/scm/ws_sql.ecm
=> WSSQL-36 ExecutePrepared cannot limit results

esp/services/ws_sql/SQL2ECL/HPCCFile.hpp, esp/services/ws_sql/SQL2ECL/HPCCFileCache.cpp
=> WSSQL-58 Report dfu file owner

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml, docs/common/Version.xml
=> WSSQL-56 Update docs for 5.2 release

esp/services/ws_sql/SQL2ECL/ANTLR3c/HPCCSQL.g, esp/services/ws_sql/SQL2ECL/HPCCFileCache.cpp, esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp, esp/services/ws_sql/ws_sqlService.cpp
- Add "<ID>.*" and <function>(*) support
- Added some log statements
=> WSSQL-68 Add SQL wilcard support

esp/services/ws_sql/SQL2ECL/ANTLR3c/HPCCSQL.g
=> WSSQL-75 Add support for quoted aliases

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
=> WSSQL-76 DOCS: Replace TargetCluster with TargetQueryset for CALL

esp/services/ws_sql/SQL2ECL/ANTLR3c/HPCCSQL.g, esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp
=> WSSQL-77 Allow schema name

esp/services/ws_sql/SQL2ECL/ECLEngine.cpp, esp/services/ws_sql/SQL2ECL/ECLEngine.hpp, esp/services/ws_sql/SQL2ECL/HPCCFile.hpp
=> WSSQL-82 Fix index annotations

esp/services/ws_sql/SQL2ECL/ECLEngine.cpp
@RussWhitehead  please review 1a4ff7f
=> Wssql 84 fixindexedquerysanslimit

esp/services/ws_sql/ws_sqlService.cpp, esp/services/ws_sql/ws_sqlService.hpp
esp/services/ws_sql/ws_sqlService.cpp lines 535-633 shifted right by one char
=> WSSQL-86 Attach original and normalized SQL to ECL query

esp/services/ws_sql/SQL2ECL/ECLEngine.cpp
=> WSSQL-84 Fix formatted strings

esp/services/ws_sql/ws_sqlService.cpp
=> WSSQL-90 Fix build break due to API signature change in HPCC Plat

esp/services/ws_sql/SQL2ECL/ECLEngine.cpp
=> WSSQL-87 account for literal value function parameters

esp/services/ws_sql/ws_sqlService.cpp, version.cmake
https://github.com/hpcc-systems/wssql/pull/61
=> Wssql 90 fix buildbreak caused by platform fn change

esp/services/ws_sql/SQL2ECL/ECLEngine.cpp
=> WSSQL-34 Output WU results to file

esp/services/ws_sql/SQL2ECL/ECLEngine.cpp, esp/services/ws_sql/ws_sqlService.cpp, esp/services/ws_sql/ws_sqlService.hpp
- Add count (outputdataset)
- restructure generated ECL in order to accommodate count
- fetch second result dataset
=> WSSQL-19 Add total count information

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
@rpastrana Please review and merge when approved
=> WsSQL-91 Document Result sets from SELECT

esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp
=> WSSQL-92 Account for "having" and ASC/DESC when normalizing

esp/services/ws_sql/ws_sqlService.hpp
=> WSSQL-94 Remove build time warnings

CMakeLists.txt, esp/scm/ws_sql.ecm, esp/services/ws_sql/ws_sqlService.cpp, esp/services/ws_sql/ws_sqlService.hpp
=> WSSQL-67 Added WSSQL build version info

esp/services/ws_sql/ws_sqlService.cpp
=> WSSQL-67 Appending result schema to prepareSQL responses

esp/services/ws_sql/ws_sqlService.cpp
=> WSSQL-64 Sets all wssql jobs as "WsSQL Job"

wssql-build-config.h.cmake
=> WSSQL-69 Add file to be used by cmake to create macro at build time

esp/scm/ws_sql.ecm, esp/services/ws_sql/SQL2ECL/HPCCFile.hpp, esp/services/ws_sql/ws_sqlService.cpp, esp/services/ws_sql/ws_sqlService.hpp
=> WSSQL-96 Add SQL create and load method

esp/services/ws_sql/SQL2ECL/HPCCFileCache.cpp, esp/services/ws_sql/SQL2ECL/HPCCFileCache.hpp, esp/services/ws_sql/ws_sqlService.cpp
=> WSSQL-100 Add option to fetch hpcc files without ECL record layout

esp/scm/ws_sql.ecm, esp/services/ws_sql/ws_sqlService.cpp, esp/services/ws_sql/ws_sqlService.hpp
- Add enumerations for data and field types
- Make file name absolute when setting description
- Improve error messages
=> WSSQL-101 Usability changes based on review

esp/services/ws_sql/SQL2ECL/HPCCFile.cpp
=> WSSQL-102 Add AbsoluteFileID as eligible files

esp/services/ws_sql/SQL2ECL/ANTLR3c/HPCCSQL.g, esp/services/ws_sql/SQL2ECL/ECLEngine.cpp, esp/services/ws_sql/SQL2ECL/ECLEngine.hpp, esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp, esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.hpp, esp/services/ws_sql/ws_sqlService.cpp
- Add CREATE and LOAD grammar and structure resulting tree
- Add ECLEngine logic to generate ECL
- If LandingZone info provided add syntax for landing zone file fetch
=> WSSQL-105 AddSQLCreateLoadSyntax

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
@rpastrana Please review and merge if ok
=> WSSQL-97 Update WsSQl docs for 5.4

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
=> WSSQL-113 Fix USEINDEX parameter docs and fix typos

esp/scm/ws_sql.ecm
=> WSSQL-106 Add UDECIMAL Type

esp/services/ws_sql/SQL2ECL/ECLEngine.cpp, esp/services/ws_sql/ws_sqlService.cpp
=> WSSQL-114 Create and Load now returns results and schema

esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp
=> WSSQL-110 Add "DISTINCT" to normalized query when appropriate

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
=> WSSQL-119 Fix Indentation on tables in Method docs

CMakeLists.txt
=> WSSQL-103 Update ver point report to match platform

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
=> WSSQL-108 Document SQL language support for Create/ Load

cmake_modules/commonSetup.cmake
Signed-off-by: Michael Gardner <Michael.Gardner@lexisnexis.com>
=> HPCC-14297 Added quick fix to wssql for beta

cmake_modules/buildANTLR3c.cmake, esp/services/ws_sql/CMakeLists.txt
Signed-off-by: Michael Gardner <michael.gardner@lexisnexis.com>
=> WSSQL-122-3 patch

esp/services/ws_sql/SQL2ECL/HPCCFileCache.cpp
=> WSSQL-127 GetDBMetaData should report super files

esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp
=> WSSQL-128 Consider aggregate funtion params when verifying sortby grpby

esp/scm/additional.cmake
Signed-off-by: Michael Gardner <Michael.Gardner@lexisnexis.com>
=> WSSQL-129 Removed deprecated GET_TARGET_PROPERTY and replaced with target generator

esp/services/ws_sql/SQL2ECL/HPCCFile.cpp, esp/services/ws_sql/SQL2ECL/HPCCFileCache.cpp, esp/services/ws_sql/ws_sqlService.cpp
=> WSSQL-130 Add TxSummary infomation

cmake_modules/commonSetup.cmake
=> WSSQL-133 Address issue due to commonsetup change in platform

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
=> WSSQL-132 Remove Tech Preview disclaimer from Docs

cmake_modules/dependencies/xenial.cmake.in
=> WSSQL-135 Add xenail dependency file

esp/scm/ws_sql.ecm, esp/services/ws_sql/ws_sqlService.cpp, esp/services/ws_sql/ws_sqlService.hpp
=> WSSQL-137 Adds support for target cluster switching

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
=> WSSQL-138 Document MultiTarget feature

README.md, esp/scm/ws_sql.ecm
- Address confusing wording
- Reformat list to markup syntax
=> WSSQL-141 Update readme file

CMakeLists.txt, cmake_modules/buildANTLR3c.cmake
=> WSSQL-123 Cmake updates

cmake_modules/buildANTLR3c.cmake
=> WSSQL-146 Do not attempt to build for 64 bit if 32 bit system

esp/scm/ws_sql.ecm, esp/services/ws_sql/SQL2ECL/ECLEngine.cpp, esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp, esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.hpp, esp/services/ws_sql/SQL2ECL/SQLExpression.cpp, esp/services/ws_sql/SQL2ECL/SQLExpression.hpp, esp/services/ws_sql/ws_sqlService.cpp, esp/services/ws_sql/ws_sqlService.hpp
Signed-off-by: rpastrana rodrigo.pastrana@lexisnexis.com
=> WSSQL-148 Improve ad-hock query caching

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
=> WsSQL-125 Document Params must be passed in order

esp/services/ws_sql/ws_sqlService.cpp
- Extract published query current WUID
- Use WUID as part of query cache key
=> WSSQL-147 Publish queries can change underlying WU

esp/scm/ws_sql.ecm, esp/services/ws_sql/ws_sqlService.cpp
- Do not attempt to clone cached queries
=> WSSQL-151 Clone and run WU doesn't seem to work

esp/scm/ws_sql.ecm, esp/services/ws_sql/ws_sqlService.cpp
=> WSSQL-154 Trim quotes off of input params

esp/services/ws_sql/ws_sqlService.cpp
- Assigns loglevel to all addTraceSummaryTimeStamp instances
=> WSSQL-156 Necessary changes to build vs HPCC 6.4

esp/services/ws_sql/ws_sqlService.cpp
- Strips quotes from input params
=> WSSQL-152 Execute prepared processes quoted input params

esp/services/ws_sql/ws_sqlService.cpp, esp/services/ws_sql/ws_sqlService.hpp
=> WSSQL-166 Prepared queries are given a name, and SQL is aligned

esp/services/ws_sql/SQL2ECL/ANTLR3c/HPCCSQL.g, esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp, esp/services/ws_sql/SQL2ECL/SQLExpression.cpp, esp/services/ws_sql/SQL2ECL/SQLExpression.hpp
- Adds 'LIKE' and 'NOT LIKE' operator support
- Maps LIKE op to ECL STD.Str.WildMatch function
=> WSSQL-70 Provide String Wildcard support

docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml
=> WSSQL-169 Document LIKE support

.gitmodules, CMakeLists.txt, README.md
Signed-off-by: Michael Gardner <michael.gardner@lexisnexis.com>
=> WSSQL-157 Platform as submodule

CMakeLists.txt
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>
=> Document build fix for candidate 6.4.0

.gitmodules, CMakeLists.txt, README.md, cmake_modules/FindANTLR.cmake, docs/WsSQLUG/WsSQL_ESPWebServiceGuide.xml, esp/services/ws_sql/CMakeLists.txt, esp/services/ws_sql/SQL2ECL/ANTLR3c/HPCCSQL.g, esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.cpp, esp/services/ws_sql/SQL2ECL/HPCCSQLTreeWalker.hpp, esp/services/ws_sql/SQL2ECL/SQLExpression.cpp, esp/services/ws_sql/SQL2ECL/SQLExpression.hpp, esp/services/ws_sql/ws_sqlService.cpp, esp/services/ws_sql/ws_sqlService.hpp, version.cmake
=> Merge candidate-6.4.0 to master
